### ISSUE TITLE
雷达分支需要图像文件吗

### ISSUE THREAD

**Issue by vanelyang** [Rorisis/Co-Occ#2]
使用 nusc_lidar.pth  预训练模型做评估，配置文件使用 coocc_lidar.py，报错信息提示缺少图片文件，请问使用雷达分支也需要图片吗？

**Comment by Rorisis** [comment]
Thanks for your questions. We apologize for uploading the incorrect version. We have made modifications to the codes in the LiDAR branch for your reference.

**Comment by vanelyang** [comment]
> Thanks for your questions. We apologize for uploading the incorrect version. We have made modifications to the codes in the LiDAR branch for your reference.

Thanks very much.

**Comment by algo-scope** [comment]
Hello, I use `bash tools/dist_test.sh projects/configs/coocc_nusc/coocc_lidar.py nusc_lidar.pth 1 --pred-save pred_result_lidar` to evaluate lidar version, but I got this error:
```
  File "Co-Occ-main/projects/mmdet3d_plugin/coocc/apis/test.py", line 217, in custom_multi_gpu_test
    save_output_nuscenes(data['gt_depths'],
KeyError: 'gt_depths'
```
Do you have any idea?

==============================
update: 
I can run by `python tools/test.py projects/configs/coocc_nusc/coocc_lidar.py nusc_lidar.pth --eval=bbox`

**Comment by algo-scope** [comment]
> Thanks for your questions. We apologize for uploading the incorrect version. We have made modifications to the codes in the LiDAR branch for your reference.

Sorry but I cannot find the LIDAR branch
