### ISSUE TITLE
Train and eval on the OpenOccupancy benchmark

### ISSUE THREAD

**Issue by HR-zju** [Rorisis/Co-Occ#5]
Hello Rorisis,
First and foremost, thank you for your incredible work and dedication to this project.
I am currently attempting to use Co-Occ to train on the **OpenOccupancy benchmark**. However, I am having difficulty finding a reference config file to guide me through this process.
Could you kindly provide a reference config file or point me to any documentation that might assist me in setting this up correctly? @Rorisis

**Comment by Rorisis** [comment]
Thanks for your question. We have uploaded the [config](https://github.com/Rorisis/Co-Occ/blob/main/projects/configs/coocc_nusc/coocc_multi_r101_openoccupancy.py) for the openoccupancy benchmark and the model weights in the readme.

**Comment by ryontang** [comment]
> Hello Rorisis, First and foremost, thank you for your incredible work and dedication to this project. I am currently attempting to use Co-Occ to train on the **OpenOccupancy benchmark**. However, I am having difficulty finding a reference config file to guide me through this process. Could you kindly provide a reference config file or point me to any documentation that might assist me in setting this up correctly? [@Rorisis](https://github.com/Rorisis)

Hi, I was wondering if you used Co-Occ for training on the OpenOccupancy benchmark. If so, how did it perform?
